### ISSUE TITLE
_.deepFind won't work with _.matches shorthand

### ISSUE THREAD

**Issue by Yimiprod** [marklagendijk/lodash-deep#35]
_.deepFind(objs, {'json.ref': objRef});
return the first item in obs even if json.ref dont match objRef.

**Comment by marklagendijk** [comment]
This is [by design](https://github.com/marklagendijk/lodash-deep#_deeppluckstylecollection-propertypath). Currently all these functions take two parameters: collection and propertyPath.
I should investigate if it would make sense to create a `_.deepMatches` method, and apply it to the appropriate `_.deep*` methods we currently have.

**Comment by jmsherry** [comment]
Am I wrong in that I find that if you do specify the matches shorthand it still returns something? (possibly the first member of the collection)

var test = [{id: 1, ingredient: {id: 11, name: 'jake'}}, {id: 2, ingredient: {id: 22, name: 'phil'}}];
_.deepFind(test, {'ingredient.name': 'phil'}); <-- results in the first obj being returned.

I think people might have expected the match syntax to work because it's in find in Lodash - having it would be super handy!

One thing, I can't work out how you're supposed to use the propertypath to achieve a find. I specify the collection and the propertypath (in my case 'ingredient.name', but how do you specify the value it's trying to match? 

Thanks, and great library btw... :)

**Comment by marklagendijk** [comment]
Since 3.7 Lodash supports using property paths in all its (relevant) methods. So you can just use:

``` javascript
var test = [{id: 1, ingredient: {id: 11, name: 'jake'}}, {id: 2, ingredient: {id: 22, name: 'phil'}}];
_.find(test, 'ingredient.name', 'phil');
```

**Comment by jmsherry** [comment]
Ok, thanks. :)
